vim.keymap.set("n", "n", function()
	pcall(vim.cmd, "normal! " .. vim.v.count1 .. "n")
	require("hlslens").start()
end, { noremap = true, silent = true })
vim.keymap.set("n", "N", function()
	pcall(vim.cmd, "normal! " .. vim.v.count1 .. "N")
	require("hlslens").start()
end, { noremap = true, silent = true })

vim.keymap.set({ "n", "x" }, "*", function()
	require("hlslens").start()
end, {})
vim.keymap.set({ "n", "x" }, "g*", function()
	require("hlslens").start()
end, {})
