git:
  paging:
    colorArg: "always"
    pager: "delta --dark --paging=never"
gui:
  language: "en"
  showIcons: true
keybinding:
  universal:
    quit: "<Esc>"
    return: "q"
    prevBlock-alt: "<C-k>" # goto the previous block / panel
    nextBlock-alt: "<C-j>" # goto the next block / panel
  commits:
    moveDownCommit: ""
    moveUpCommit: ""
